### ISSUE TITLE
tls: internal error on the cluster and see you refer to a potential solution?

### ISSUE THREAD

**Issue by mannp** [zimmertr/TJs-Kubernetes-Service#36]
Talos 1.5.3, k8s 1.28.2

[TLS Issue](https://github.com/kubernetes/kubeadm/issues/591)

Hi and thanks for sharing your setup :)

New to talos and k8s (been using k3s) and have an issue with internal certs not getting signed.

All the csr are 'denied' and I am unable to get the metrics server working amongst other things.

You refer in the link to that thread being the solution, but I am not so sure how that relates here?

Any pointers would be a great help to get the cluster core up and running :)

Thanks

**Comment by mannp** [comment]
Thanks for the detailed response, much appreciated.

So yes I have created DHCP reservations for all the nodes in opnsense.

The cluster is isolated on its own vlan 16 and the dns is configured for that vlan.

I will need to test connectivity further tomorrow (time for sleep in a bit :) )

> ```shell
> kubectl get csr
> ```
```
csr-zxlx2   55m     kubernetes.io/kubelet-serving   system:node:cp-2     <none>              Denied
csr-zxrxp   38m     kubernetes.io/kubelet-serving   system:node:cp-3     <none>              Denied
csr-zxtjk   61m     kubernetes.io/kubelet-serving   system:node:node-2   <none>              Denied
csr-zz7kp   72m     kubernetes.io/kubelet-serving   system:node:cp-2     <none>              Denied
```
I am unable to alter these as it states they are already denied.

> How are you installing `metrics server` and why isn't it working? Are you using my collection of `core` apps [here](https://github.com/zimmertr/Kubernetes-Manifests/tree/main/core)?

Yes for the moment I am using all of your setup, so I can get familiar with it all.

> Are you using Flannel, Cilium, or a different CNI? In my experience, when I used Flannel (Talos default) I had no issues with certificates. However, when I disabled Flannel via [var.talos_disable_flannel](https://github.com/zimmertr/TJs-Kubernetes-Service/blob/main/variables.tf#L57) and installed Cilium via the above linked Core apps, I encountered `Pending` certificates. Which is when I found that thread and commented in it. My manual solution then was simply to:

I disabled flannel and installed cilium using your core.


> Can you share your TFVars file?

```
# Proxmox #######################
proxmox_hostname                = "pm01.m.local"
proxmox_ssh_key_path            = "/home/local/nixos-shared/........."
proxmox_resource_pool           = "m-stable"
# Talos #########################
talos_image_node_name           = "pm01"
talos_virtual_ip                = "192.168.16.10"
talos_disable_flannel           = "true"               # disable to add cilium
# Kubernetes ####################
kubernetes_cluster_name         = "m-stable"
# Controlplanes #################
controlplane_vmid_prefix        = "1001"               # 1001-1019
controlplane_node_name          = "pm01"
controlplane_datastore          = "local"
controlplane_cpu_cores          = "2"
controlplane_memory             = "3072"
controlplane_disk_size          = "10"
controlplane_num                = "3"
controlplane_hostname_prefix    = "cp"
controlplane_ip_prefix          = "192.168.16.1"      # 1-9
controlplane_mac_address_prefix = "00:00:00:00:16:1"  # 00:11 - 00:19
controlplane_vlan_id            = "16"
controlplane_tags               = [
  "app-kubernetes",
  "clusterid-stable",
  "type-controlplane"
]
# Worker Nodes ##################
workernode_vmid_prefix          = "1002"               # 1002-1029
workernode_node_name            = "pm01"
workernode_datastore            = "local"
workernode_cpu_cores            = "2"
workernode_memory               = "10240"
workernode_disk_size            = "10"
workernode_num                  = "2"
workernode_hostname_prefix      = "node"
workernode_ip_prefix            = "192.168.16.2"      # 21-29
workernode_mac_address_prefix   = "00:00:00:00:16:2"  # 00:21 - 00:29
workernode_vlan_id              = "16"
workernode_tags                 = [
  "app-kubernetes",
  "clusterid-stable",
  "type-workernode"
]

```

**Comment by zimmertr** [comment]
Unless you have a need for it, Flannel is a perfectly fine CNI. I just wanted to use Cilium to learn about eBPF and the alternatives to Istio. 

That being said, I can't replicate your issue on my side so I'm unable to troubleshoot. (I'm also generally unfamiliar with this side of Kubernetes to begin with). 

I looked at the [documentation](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#approval-rejection-api-client) for certificates and saw that a denied CSR has a condition with an associated Reason and Message. For example (from the docs):

```yaml
status:
  conditions:
  - lastUpdateTime: "2020-02-08T11:37:35Z"
    lastTransitionTime: "2020-02-08T11:37:35Z"
    message: Denied by my custom approver controller
    reason: DeniedByMyPolicy # You can set this to any string
    type: Denied
```

Are you able to `kubectl describe` or `kubectl edit` the denied CSRs to get an indication of the reason? 

It also says [above](url) in the documentation that denied requests are removed after an hour, FYI.

**Comment by bhargav2427** [comment]
In my case, the issue was with the aws-auth config map. In the aws-auth configmap, my nodes entry was as follows, which is incorrect.

```
    - groups:
      - system:masters
      rolearn: arn:aws:iam::ACCOUNT_ID:role/IAM_ROLE
      username: XXX
```

It should be like

```
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::ACCOUNT_ID:role/IAM_ROLE
      username: system:node:{{EC2PrivateDNSName}}
```

**If you are encountering this issue, there may be some problems with node RBAC in Kubernetes. It's worth checking.**

**Comment by zimmertr** [comment]
How in the world did my project get involved with EKS? Lol. Are you joining Proxmox hosted nodes using this project to an EKS cluster?

**Comment by mannp** [comment]
I have spent time destroying and spinning up clusters with varying results.

None of which were conclusive though or pointed me to any issue.

This can be closed for me, as having to get other things sorted before circling back around to this again 🙂
